# Spring Application config
spring.application.name=banking
logging.level.root=warn

# App Security Variables
app.security.jwt-secret=C0llzYABKThIywccGLUb+R4clCvZEa4/FwCrDwuvdqs=

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.drop-first=true

# Spring security
logging.level.org.springframework.security=WARN

# API path
server.servlet.context-path=/api

# Websocket
#logging.level.org.springframework.web.socket=DEBUG
#logging.level.org.springframework.messaging=DEBUG

# Metrics
management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus,metrics